name: GHAction example  

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Secure multi-arch Docker build with scan and push
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/example
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   
            type=raw,value=latest

      - name: QEMU setup (multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Buildx setup
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          outputs: type=docker
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example-cache:buildcache
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example-cache:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}

      - name: Scan Docker image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/example:latest
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Push image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example-cache:buildcache
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example-cache:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
